// <auto-generated />
using System;
using BarberDario.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BarberDario.Api.Migrations
{
    [DbContext(typeof(BarberDarioDbContext))]
    [Migration("20251227153042_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BarberDario.Api.Data.Entities.BlockedTimeSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BlockDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BlockDate");

                    b.ToTable("BlockedTimeSlots");
                });

            modelBuilder.Entity("BarberDario.Api.Data.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ConfirmationSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerNotes")
                        .HasColumnType("text");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime?>("ReminderSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BookingDate");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("Status");

                    b.HasIndex("BookingDate", "Status");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BarberDario.Api.Data.Entities.BusinessHours", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeOnly?>("BreakEndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("BreakStartTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("CloseTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly>("OpenTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DayOfWeek")
                        .IsUnique();

                    b.ToTable("BusinessHours");

                    b.HasData(
                        new
                        {
                            Id = new Guid("02783d14-b505-4380-ada6-42e28cb1719e"),
                            CloseTime = new TimeOnly(0, 0, 0),
                            DayOfWeek = 0,
                            IsOpen = false,
                            OpenTime = new TimeOnly(0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("a4cf0422-a981-4763-a779-9bd8bba6dbfc"),
                            CloseTime = new TimeOnly(18, 0, 0),
                            DayOfWeek = 1,
                            IsOpen = true,
                            OpenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("f3023f62-21b1-48e2-bfcf-cf6a70f211cc"),
                            CloseTime = new TimeOnly(18, 0, 0),
                            DayOfWeek = 2,
                            IsOpen = true,
                            OpenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("1c9975f3-edff-4a76-ab99-9a93b99a31c2"),
                            CloseTime = new TimeOnly(18, 0, 0),
                            DayOfWeek = 3,
                            IsOpen = true,
                            OpenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("67448c16-2157-4153-a41b-2ccb73cb4a4f"),
                            CloseTime = new TimeOnly(20, 0, 0),
                            DayOfWeek = 4,
                            IsOpen = true,
                            OpenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("703275df-27e2-41a5-8d45-8f4c3216228e"),
                            CloseTime = new TimeOnly(18, 0, 0),
                            DayOfWeek = 5,
                            IsOpen = true,
                            OpenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("5abe3aca-36b6-4c79-9945-bfb4c4864536"),
                            CloseTime = new TimeOnly(16, 0, 0),
                            DayOfWeek = 6,
                            IsOpen = true,
                            OpenTime = new TimeOnly(9, 0, 0)
                        });
                });

            modelBuilder.Entity("BarberDario.Api.Data.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastVisit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NoShowCount")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TotalBookings")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BarberDario.Api.Data.Entities.EmailLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("EmailType");

                    b.ToTable("EmailLogs");
                });

            modelBuilder.Entity("BarberDario.Api.Data.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 12, 27, 15, 30, 41, 907, DateTimeKind.Utc).AddTicks(3490),
                            Description = "Klassischer Herrenhaarschnitt mit Styling",
                            DisplayOrder = 1,
                            DurationMinutes = 30,
                            IsActive = true,
                            Name = "Herrenschnitt",
                            Price = 35.00m,
                            UpdatedAt = new DateTime(2025, 12, 27, 15, 30, 41, 907, DateTimeKind.Utc).AddTicks(3490)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 12, 27, 15, 30, 41, 907, DateTimeKind.Utc).AddTicks(3520),
                            Description = "Professionelles Bart-Trimming und Konturenschneiden",
                            DisplayOrder = 2,
                            DurationMinutes = 20,
                            IsActive = true,
                            Name = "Bart Trimmen",
                            Price = 20.00m,
                            UpdatedAt = new DateTime(2025, 12, 27, 15, 30, 41, 907, DateTimeKind.Utc).AddTicks(3520)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 12, 27, 15, 30, 41, 907, DateTimeKind.Utc).AddTicks(3520),
                            Description = "Haarschnitt + Bart Trimmen",
                            DisplayOrder = 3,
                            DurationMinutes = 50,
                            IsActive = true,
                            Name = "Komplettpaket",
                            Price = 50.00m,
                            UpdatedAt = new DateTime(2025, 12, 27, 15, 30, 41, 907, DateTimeKind.Utc).AddTicks(3520)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2025, 12, 27, 15, 30, 41, 907, DateTimeKind.Utc).AddTicks(3530),
                            Description = "Haarschnitt für Kinder bis 12 Jahre",
                            DisplayOrder = 4,
                            DurationMinutes = 30,
                            IsActive = true,
                            Name = "Kinder Haarschnitt",
                            Price = 25.00m,
                            UpdatedAt = new DateTime(2025, 12, 27, 15, 30, 41, 907, DateTimeKind.Utc).AddTicks(3530)
                        });
                });

            modelBuilder.Entity("BarberDario.Api.Data.Entities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Key = "BOOKING_INTERVAL_MINUTES",
                            Description = "Zeitintervall für Buchungen in Minuten",
                            UpdatedAt = new DateTime(2025, 12, 27, 15, 30, 41, 907, DateTimeKind.Utc).AddTicks(3710),
                            Value = "15"
                        },
                        new
                        {
                            Key = "MAX_ADVANCE_BOOKING_DAYS",
                            Description = "Wie viele Tage im Voraus kann gebucht werden",
                            UpdatedAt = new DateTime(2025, 12, 27, 15, 30, 41, 907, DateTimeKind.Utc).AddTicks(3710),
                            Value = "60"
                        },
                        new
                        {
                            Key = "MIN_ADVANCE_BOOKING_HOURS",
                            Description = "Mindestvorlauf für Buchungen in Stunden",
                            UpdatedAt = new DateTime(2025, 12, 27, 15, 30, 41, 907, DateTimeKind.Utc).AddTicks(3720),
                            Value = "24"
                        },
                        new
                        {
                            Key = "REMINDER_HOURS_BEFORE",
                            Description = "Wann vor dem Termin wird die Erinnerung gesendet (Stunden)",
                            UpdatedAt = new DateTime(2025, 12, 27, 15, 30, 41, 907, DateTimeKind.Utc).AddTicks(3720),
                            Value = "24"
                        },
                        new
                        {
                            Key = "ADMIN_EMAIL",
                            Description = "Admin Email-Adresse",
                            UpdatedAt = new DateTime(2025, 12, 27, 15, 30, 41, 907, DateTimeKind.Utc).AddTicks(3720),
                            Value = "dario@barberdario.com"
                        },
                        new
                        {
                            Key = "BUSINESS_NAME",
                            Description = "Name des Geschäfts",
                            UpdatedAt = new DateTime(2025, 12, 27, 15, 30, 41, 907, DateTimeKind.Utc).AddTicks(3720),
                            Value = "Barber Dario"
                        },
                        new
                        {
                            Key = "BUSINESS_ADDRESS",
                            Description = "Geschäftsadresse",
                            UpdatedAt = new DateTime(2025, 12, 27, 15, 30, 41, 907, DateTimeKind.Utc).AddTicks(3720),
                            Value = "Berliner Allee 43, 40212 Düsseldorf"
                        },
                        new
                        {
                            Key = "TIMEZONE",
                            Description = "Zeitzone des Geschäfts",
                            UpdatedAt = new DateTime(2025, 12, 27, 15, 30, 41, 907, DateTimeKind.Utc).AddTicks(3720),
                            Value = "Europe/Berlin"
                        });
                });

            modelBuilder.Entity("BarberDario.Api.Data.Entities.Booking", b =>
                {
                    b.HasOne("BarberDario.Api.Data.Entities.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarberDario.Api.Data.Entities.Service", "Service")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BarberDario.Api.Data.Entities.EmailLog", b =>
                {
                    b.HasOne("BarberDario.Api.Data.Entities.Booking", "Booking")
                        .WithMany("EmailLogs")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BarberDario.Api.Data.Entities.Booking", b =>
                {
                    b.Navigation("EmailLogs");
                });

            modelBuilder.Entity("BarberDario.Api.Data.Entities.Customer", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("BarberDario.Api.Data.Entities.Service", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
